name: Docs
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
    docs:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master

        - uses: actions/setup-node@v2
        - name: Add Missing Contributors
          env:
            PRIVATE_TOKEN: ${{ github.token }}
          run: |
            yarn add all-contributors-cli
            # Fetch Contributors and Add them
            CONTRIBUTORS="$(yarn all-contributors check)"
            CONTRIBUTORS=$(echo $CONTRIBUTORS | sed -E 's/^.*all-contributors check//g' | sed -E 's/Missing contributors in .all-contributorsrc: //g' | sed -E 's/Unknown contributors.*//g' | sed -E 's/Done in.*//g' | sed 's/^[ \t]*//;s/[ \t]*$//' | sed -E 's/\,//g')
            # Add Contributors (code)
            if [ -z $CONTRIBUTORS ]; then
              echo "Everyone has been awarded credits! :D"
            else
              echo "Adding Contributors $CONTRIBUTORS"
              echo $CONTRIBUTORS | xargs -d " " -I '{}'  yarn all-contributors add {} code
            fi

        - name: Generate Contributors Table
          run: |
            yarn all-contributors generate

        - name: Generate docs
          run: |
            npm i
            npm run docs

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs
            cname: materializeweb.com
            exclude_assets: node_modules
            user_name: 'github-actions[bot]'
            user_email: 'github-actions[bot]@users.noreply.github.com'

